### PR TITLE
Translate Pt-br and change field size name

### PR DESCRIPTION
**Pull request by juniogro10**

### CODE REVIEW

**Comment by cooltechworks** [comment]
@juniogro10 first commit (8654326) is fine. The second commit(9e6b624) seems to be you have pushed the binary files which are unnecessary.

**Comment by juniogro10** [comment]
My github given problem in time to commit the (8654326) has some modified files, along with not necessary binary.
The (9e6b624) was forced to certain files was not commit.

**Comment by cooltechworks** [comment]
Can you revert those unnecessary changes and again send a new pull request? Btw, the AMEX card have an image that appears in the center for which the following code is introduced. Your changelist 99cb2d broke that. Please revert that one as well.

```java
 if(cardNumber.startsWith(AMEX_PREFIX)) {
                 return AMEX;
             }
```

**Comment by juniogro10** [comment]
After this last response I stopped to read some of your code.

The logic of current treatment leaves too caught code.
I realized that after the need to create new types of cards.

This logic worked for me because it does not work for you?

**Comment by sharish** [comment]
None working on this change. Closing this pull request.

**Pull request closed without merging**
